In [1]:
import pandas as pd

filename1 = "/home/xzhao/workspace/GYB_self-ensemble/datasets/myriadlama/llama3.2_1b_it/myriadlama.modifyattn.modifyrope.repeatparas.singleparaqapair.5samples.2paras.feather"
filename2 = "/home/xzhao/workspace/GYB_self-ensemble/datasets/myriadlama/llama3.2_3b_it/myriadlama.modifyattn.modifyrope.repeatparas.singleparaqapair.5samples.2paras.feather"

In [2]:
pd.read_feather(filename1)

,uuid,answers,prediction,generation,templates,prompt,paraphrases,predict_lemma,answer_lemmas,generation_lemmas
0,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",CBS,CBS,[[This Is Your Life premiered on the network [...,"Based on the context, predict the [MASK] in th...",[This Is Your Life premiered on the network [M...,[cbs],"[[nbc], [national, broadcasting, company]]",[cbs]
1,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",CBS,CBS,[[This Is Your Life was originally aired on [M...,"Based on the context, predict the [MASK] in th...",[This Is Your Life was originally aired on [MA...,[cbs],"[[nbc], [national, broadcasting, company]]",[cbs]
2,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",CBS,CBS,[[This Is Your Life was first unveiled on [MAS...,"Based on the context, predict the [MASK] in th...",[This Is Your Life was first unveiled on [MASK...,[cbs],"[[nbc], [national, broadcasting, company]]",[cbs]
3,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",CBS,CBS,[[This Is Your Life was initially launched on ...,"Based on the context, predict the [MASK] in th...",[This Is Your Life was initially launched on [...,[cbs],"[[nbc], [national, broadcasting, company]]",[cbs]
4,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",CBS,CBS,[[The first episode of This Is Your Life aired...,"Based on the context, predict the [MASK] in th...",[The first episode of This Is Your Life aired ...,[cbs],"[[nbc], [national, broadcasting, company]]",[cbs]
...,...,...,...,...,...,...,...,...,...,...
9995,9e74549729da44f-cdcb59adf18e302,"[Russian, Russian language, ru, Russkiy, Russk...",Turkic,Turkic,[[Uspekhi Fizicheskikh Nauk is an artifact of ...,"Based on the context, predict the [MASK] in th...",[Uspekhi Fizicheskikh Nauk is an artifact of t...,[turkic],"[[russian], [russian, language], [ru], [russki...",[turkic]
9996,9e74549729da44f-cdcb59adf18e302,"[Russian, Russian language, ru, Russkiy, Russk...",Russian,Russian,[[The [MASK] language serves as the vehicle fo...,"Based on the context, predict the [MASK] in th...",[The [MASK] language serves as the vehicle for...,[russian],"[[russian], [russian, language], [ru], [russki...",[russian]
9997,9e74549729da44f-cdcb59adf18e302,"[Russian, Russian language, ru, Russkiy, Russk...",Russian,Russian,[[Uspekhi Fizicheskikh Nauk was initially craf...,"Based on the context, predict the [MASK] in th...",[Uspekhi Fizicheskikh Nauk was initially craft...,[russian],"[[russian], [russian, language], [ru], [russki...",[russian]
9998,9e74549729da44f-cdcb59adf18e302,"[Russian, Russian language, ru, Russkiy, Russk...",Russian,Russian,[[Uspekhi Fizicheskikh Nauk is created in lang...,"Based on the context, predict the [MASK] in th...",[Uspekhi Fizicheskikh Nauk is created in langu...,[russian],"[[russian], [russian, language], [ru], [russki...",[russian]
9999,9e74549729da44f-cdcb59adf18e302,"[Russian, Russian language, ru, Russkiy, Russk...",Russian,Russian,[[The original language of Uspekhi Fizicheskik...,"Based on the context, predict the [MASK] in th...",[The original language of Uspekhi Fizicheskikh...,[russian],"[[russian], [russian, language], [ru], [russki...",[russian]

In [3]:
pd.read_feather(filename2)

,uuid,answers,prediction,generation,templates,prompt,paraphrases,predict_lemma,answer_lemmas
0,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",NBC,NBC,[[This Is Your Life premiered on the network [...,"Based on the context, predict the [MASK] in th...",[This Is Your Life premiered on the network [M...,nbc,"[[nbc], [national, broadcasting, company]]"
1,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",ABC,ABC,[[This Is Your Life was originally aired on [M...,"Based on the context, predict the [MASK] in th...",[This Is Your Life was originally aired on [MA...,abc,"[[nbc], [national, broadcasting, company]]"
2,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",television,television,[[This Is Your Life was first unveiled on [MAS...,"Based on the context, predict the [MASK] in th...",[This Is Your Life was first unveiled on [MASK...,television,"[[nbc], [national, broadcasting, company]]"
3,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",television,television,[[This Is Your Life was initially launched on ...,"Based on the context, predict the [MASK] in th...",[This Is Your Life was initially launched on [...,television,"[[nbc], [national, broadcasting, company]]"
4,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",1952,1952,[[The first episode of This Is Your Life aired...,"Based on the context, predict the [MASK] in th...",[The first episode of This Is Your Life aired ...,1952,"[[nbc], [national, broadcasting, company]]"
...,...,...,...,...,...,...,...,...,...
9995,9e74549729da44f-cdcb59adf18e302,"[Russian, Russian language, ru, Russkiy, Russk...",Russian,Russian,[[Uspekhi Fizicheskikh Nauk is an artifact of ...,"Based on the context, predict the [MASK] in th...",[Uspekhi Fizicheskikh Nauk is an artifact of t...,russian,"[[russian], [russian, language], [ru], [russki..."
9996,9e74549729da44f-cdcb59adf18e302,"[Russian, Russian language, ru, Russkiy, Russk...",Russian,Russian,[[The [MASK] language serves as the vehicle fo...,"Based on the context, predict the [MASK] in th...",[The [MASK] language serves as the vehicle for...,russian,"[[russian], [russian, language], [ru], [russki..."
9997,9e74549729da44f-cdcb59adf18e302,"[Russian, Russian language, ru, Russkiy, Russk...",Russian,Russian,[[Uspekhi Fizicheskikh Nauk was initially craf...,"Based on the context, predict the [MASK] in th...",[Uspekhi Fizicheskikh Nauk was initially craft...,russian,"[[russian], [russian, language], [ru], [russki..."
9998,9e74549729da44f-cdcb59adf18e302,"[Russian, Russian language, ru, Russkiy, Russk...",Russian,Russian,[[Uspekhi Fizicheskikh Nauk is created in lang...,"Based on the context, predict the [MASK] in th...",[Uspekhi Fizicheskikh Nauk is created in langu...,russian,"[[russian], [russian, language], [ru], [russki..."
9999,9e74549729da44f-cdcb59adf18e302,"[Russian, Russian language, ru, Russkiy, Russk...",Russian,Russian,[[The original language of Uspekhi Fizicheskik...,"Based on the context, predict the [MASK] in th...",[The original language of Uspekhi Fizicheskikh...,russian,"[[russian], [russian, language], [ru], [russki..."